### ISSUE TITLE
Chronicles logs can raise OSError

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-chronicles#60]
I think it would be better if chronicles would not allow `OSError` to be raised, but just handled in the library. After all logging should have as minimal impact to the user code as possible.

This way the user can use `{.raises: [].}` instead of having to add `{.raises: [OSError].}`.

**Comment by arnetheduck** [comment]
would probably make sense to bail-to-stderr or something like that, so that if a disk is full or some other error happens on the primary logging target, one line is printed to some backup log facility (stderr/syslog)

**Comment by kdeme** [comment]
So, it's actually worse than just `OSError` as it also depends on the compile time options of chronicles.

Logging with a sink to a file requires `OSError`.
Logging to default stdout requires `IOError` and `ValueError`.

So practically it means adding for sure `raises[OSError, IOError, ValueError]`. Perhaps there are more...

**Comment by zah** [comment]
Possible exceptions may come from serialization and from writing to the target sink. Since logging is usually not mission critical, viable strategies for handling the errors are:

* Write a messages to stderr
* Do nothing
* Handle it in some app-specific way

To cover all of these, perhaps Chronicles should simply use an user-supplied hook with a default implementation writing to `stderr`.
